# Names for Missions are taken directly from the game
main_mission_table = {
    # Act 1
    1: "Escape from Fortress",
    2: "Protect Kor and Kid",
    3: "Retrieve Banner from Dead Town",
    4: "Find Pumping Station Valve",
    5: "Blow up Ammo at Fortress",
    6: "Make delivery to Hip Hog Saloon",
    7: "Beat Scatter Gun Course",
    8: "Protect Sig at Pumping Station",
    9: "Destroy Turrets in Sewers",
    10: "Rescue Vin at Strip Mine",
    11: "Find Pumping Station Patrol",
    12: "Find Lens in Mountain Temple",
    13: "Find Gear in Mountain Temple",
    14: "Find Shard in Mountain Temple",
    15: "Beat Time to Race Garage",
    16: "Win JET-Board Stadium Challenge",
    17: "Collect Money for Krew",
    18: "Beat Blaster Gun Course",
    19: "Destroy Eggs at Drill Platform",
    20: "Turn on 5 Power Switches",
    21: "Ride Elevator up to Palace",
    22: "Defeat Baron at Palace",
    # Act 2
    23: "Shuttle Underground Fighters",
    24: "Protect Site in Dead Town",
    25: "Catch Scouts in Haven Forest",
    26: "Escort Kid to Power Station",
    27: "Destroy Equipment at Dig",
    28: "Blow up Strip Mine Eco Wells",
    29: "Destroy Ship at Drill Platform",
    30: "Destroy Cargo in Port",
    31: "Rescue Lurkers for Brutter #1",
    32: "Drain Sewers to find Statue",
    33: "Hunt Haven Forest Metal Heads",
    34: "Intercept Tanker",
    35: "Win Class 3 Race at Stadium",
    36: "Get Seal Piece at Water Slums",
    37: "Get Seal Piece at Dig",
    38: "Destroy 5 HellCat Cruisers",
    39: "Beat Onin Game",
    40: "Use items in No Man's Canyon",
    41: "Pass the first Test of Manhood",
    42: "Pass the second Test of Manhood",
    43: "Defeat Baron in Mar's Tomb",
    # Act 3
    44: "Rescue Friends in Fortress",
    45: "Escort men through Sewers",
    46: "Win Class 2 Race at Stadium",
    47: "Protect Hideout from Bombots",
    48: "Beat Erol in Race Challenge",
    49: "Destroy Eggs in Strip Mine",
    50: "Get Life Seed in Dead Town",
    51: "Protect Samos in Haven Forest",
    52: "Destroy Drill Platform Tower",
    53: "Rescue Lurkers for Brutter #2",
    54: "Win Class 1 Race at Stadium",
    55: "Explore Palace",
    56: "Get Heart of Mar in Weapons Lab",
    57: "Beat Krew in Weapons Lab",
    58: "Beat the Metal Head Mash Game",
    59: "Find Sig in Under Port",
    60: "Escort Sig in Under Port",
    61: "Defend Stadium",
    62: "Check the Construction Site",
    63: "Break Barrier at Nest",
    64: "Attack the Metal Head Nest",
    65: "Destroy Metal Kor at Nest"
}

# Names of Side Missions are taken from the Fandom Jak II Wiki
side_mission_table = {
    1: "Orb Search 1 (Computer #2)",
    2: "Orb Search 2 (Computer #3)",
    3: "Orb Search 3 (Computer #4)",
    4: "Orb Search 4 (Computer #5)",
    5: "Orb Search 5 (Computer #9)",
    6: "Orb Search 6 (Computer #10)",
    7: "Orb Search 7 (Computer #11)",
    8: "Orb Search 8 (Computer #12)",
    9: "Orb Search 9 (Computer # 6)",
    10: "Orb Search 10 (Computer #14)",
    11: "Orb Search 11 (Computer #15)",
    12: "Orb Search 12 (Computer #7)",
    13: "Orb Search 13 (Computer #16)",
    14: "Orb Search 14 (Computer #17)",
    15: "Orb Search 15 (Computer #18)",
    16: "Ring Race 1 (Computer #1)",
    17: "Ring Race 2 (Computer #8)",
    18: "Ring Race 3 (Computer #1)",
    19: "Collection 1 (Computer #6)",
    20: "Collection 2 (Computer #13)",
    21: "Collection 3 (Computer #12)",
    22: "Deliver Package Side Mission (Computer #7)",
    23: "Shuttle Underground Fighters Side Mission (Computer #7)",
    24: "Destroy Blast Bots Side Mission (Computer #7)",
    25: "Erol Race Side Mission",
    26: "Port Race Side Mission",
    27: "JET-Board Stadium Challenge Side Mission",
    28: "Class 3 Race Side Mission",
    29: "Class 2 Race Side Mission",
    30: "Class 1 Race Side Mission",
    31: "Class 3R Race Side Mission",
    32: "Class 2R Race Side Mission",
    33: "Class 1R Race Side Mission"
}